In [1]:
import sqlite3
# establishing a database connection
con = sqlite3.connect('CentralDB.sqlite')

In [7]:
cursor=con.cursor()
query = """ select distinct valueRepresentation from pipe_properties where fieldID='2030' """
#query = """select * from pipe_properties where fieldID='2030'"""
cursor.execute(query)
records = cursor.fetchall()
records

[('4 1/2',),
 ('5',),
 ('5 1/2',),
 ('6 5/8',),
 ('7',),
 ('7 5/8',),
 ('7 3/4',),
 ('8 5/8',),
 ('9 5/8',),
 ('9 3/4',),
 ('9 7/8',),
 ('10 3/4',),
 ('11 3/4',),
 ('11 7/8',),
 ('13 3/8',),
 ('13 5/8',),
 ('16',),
 ('18 5/8',),
 ('20',),
 ('1',)]

In [4]:
import pandas as pd
df = pd.read_sql('select * from fields',con)
df

,fieldID,description,representation,abbreviation,dataType,parameterID,precision,backgroundColor,altBackgroundColor,textColor,altTextColor,flag,altFlag
0,2000,Index,i,i,int,,,FFFFFF,FAFAC8,000000,FA0000,59,33
1,2001,Measured Depth,MD,MD,float,1001,2,FFFFFF,FAFAC8,000000,FA0000,59,33
2,2002,Inclination,Inc,Inc,float,1026,2,FFFFFF,FAFAC8,000000,FA0000,59,33
3,2003,Azimuth,Azi,Azi,float,1026,2,FFFFFF,FAFAC8,000000,FA0000,59,33
4,2004,True Vertical Depth,TVD,TVD,float,1001,2,FFFFFF,FAFAC8,000000,FA0000,59,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2082,Torque On Bit,Torque On Bit,TOB,float,1023,3,FFFFFF,FAFAC8,000000,FA0000,59,33
83,2083,Traveling Assebly Weight,Traveling Assebly Weight,TAW,float,1022,3,FFFFFF,FAFAC8,000000,FA0000,59,33
84,2084,Tripping speed,Tripping speed,TrV,float,1008,3,FFFFFF,FAFAC8,000000,FA0000,59,33
85,2085,Rotational speed,Rotational speed,RoR,float,1011,3,FFFFFF,FAFAC8,000000,FA0000,59,33
86,2086,Psi,Psi,Psi,float,1026,3,FFFFFF,FAFAC8,000000,FA0000,59,33

In [7]:
con.close()

In [9]:
pd.read_sql('select * from fields',con)

ProgrammingError: Cannot operate on a closed database.